### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by rcorzogutierrez** [gilsondev/facefind#1]
Great project
I tried to run the project and I could not. Console shows me this error.

>   File "......lib\site-packages\decouple.py", line 64, in get
    raise UndefinedValueError('%s option not found and default value was not defined.' % option)
decouple.UndefinedValueError: SECRET_KEY option not found and default value was not defined.

why decouple is incapable to get the value of my SECRET_KEY of the .env file?

Thank

**Comment by gilsondev** [comment]
You need copy [this file](https://github.com/gilsondev/facefind/blob/master/contrib/env.sample) and paste in root path of project
